### ISSUE TITLE
go/cgo updates for newer compilers?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/go-feedstock#141]
### Comment:

Thanks for this great enabler!

At present it seems like there are some issues installing a specific version of `compiler('cgo')` on some downstreams:

- https://github.com/conda-forge/go-ipfs-feedstock/pull/12#issuecomment-1073299127
- https://github.com/conda-forge/kubernetes-feedstock/pull/102#issuecomment-1068701747
- https://github.com/conda-forge/podman-feedstock/commit/6512d814f4ea8c3f4b9c1ee51297b7ce6d37f06a

Unfortunately, I'm something of a compiler dilettante, and wouldn't know how to go about improving the situation, aside from making it known.

**Comment by bollwyvl** [comment]
as a data point: I was able to imitate the `podman` approach to get go-ipfs to work.

**Comment by dhirschfeld** [comment]
I think the issue title isn't properly reflective of the severity of this issue. I'd be inclined to rename to something along the lines of:
```
[BUG] `go` compilers incompatible with `c` compilers
```

Yes, it *is* a little provocative, but if it turns out to be a false accusation then we can always [ask forgiveness](https://docs.python.org/3.4/glossary.html#term-eafp).

**Comment by dhirschfeld** [comment]
ping @conda-forge/go

**Comment by xhochy** [comment]
The 1.19 and 1.20 releases should no longer constrain the compilers.
