### ISSUE TITLE
Running Go on the root environment

### ISSUE THREAD

**Issue by diwangs** [conda-forge/go-feedstock#8]
I find myself unable to run a go command without activating an environment first (aka, I'm in the root environment). Whenever I tried to use a command in the root, it responses with:
`go: cannot find GOROOT directory: C:\bld\go_1517162278369\work\go`
Am I supposed to change the GOROOT directory manually or is this a bug?

I'm using Windows PowerShell with Conda 4.3.33

**Comment by nehaljwani** [comment]
@diwangs That is expected. You have to activate the environment in which go is installed to use it, because when the environment is activated, an [activated script](https://github.com/conda-forge/go-feedstock/blob/master/recipe/activate.bat) is called, which sets the GOROOT appropriately. A workaround for your use case is to run:
/path/to/env/where/go/is/installed/etc/conda/activate.d/activate.bat
